[tools]
terraform = "1.14.5"

[tasks.init]
description = "Run terraform init"
run = "terraform init"

[tasks.validate]
description = "Run terraform validate"
run = "terraform validate"

[tasks.fmt]
description = "Run terraform fmt"
run = "terraform fmt"

[tasks.plan]
description = "Run terraform plan"
run = "terraform plan"

[tasks.ci]
description = "Run check and plan"
run = [
  { task = "fmt" },
  { task = "validate" },
  { task = "plan" },
]
