[tools]
terraform = "1.9"

[tasks.init]
description = "Run terraform init"
run = "terraform init"

[tasks.validate]
description = "Run terraform validate"
run = "terraform validate"

[tasks.fmt]
description = "Run terraform fmt"
run = "terraform fmt"

[tasks.plan]
description = "Run terraform plan"
run = "terraform plan"
